#!/bin/sh

export PATH="/opt/homebrew/bin:$HOME/.local/share/mise/shims:$PATH"

[ -d "$HOME/work" ] && fd -H -d 1 -t d -E .Trash . "$HOME/work"
[ -d "$HOME/personal" ] && fd -H -d 1 -t d -E .Trash . "$HOME/personal"
[ -d "$HOME/projects" ] && fd -H -d 1 -t d -E .Trash . "$HOME/projects"
