import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[shell]
program = "tmux"
args = ["new-session", "-A", "-D", "-s", "main"]

[font]
size = 14

[window]
opacity = 0.9
option_as_alt = true

[scrolling]
history = 100000

[font]
size = 16

[font.bold]
family = "BerkeleyMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "BerkeleyMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "BerkeleyMono Nerd Font"
style = "Italic"

[font.normal]
family = "BerkeleyMono Nerd Font"
style = "Regular"


# Key bindings
[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001Bb"  # Send escape sequence for Alt+Left

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001Bf"  # Send escape sequence for Alt+Right

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u001BOH"  # Send escape sequence for Command+Left

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u001BOF"  # Send escape sequence for Command+Right

[[keyboard.bindings]]
key = "Key1"
mods = "Control"
chars = "\u001b[27;5;49~"

[[keyboard.bindings]]
key = "Key2"
mods = "Control"
chars = "\u001b[27;5;50~"

[[keyboard.bindings]]
key = "Key3"
mods = "Control"
chars = "\u001b[27;5;51~"

[[keyboard.bindings]]
key = "Key4"
mods = "Control"
chars = "\u001b[27;5;52~"

[[keyboard.bindings]]
key = "Key5"
mods = "Control"
chars = "\u001b[27;5;53~"

[[keyboard.bindings]]
key = "Key6"
mods = "Control"
chars = "\u001b[27;5;54~"

[[keyboard.bindings]]
key = "Key7"
mods = "Control"
chars = "\u001b[27;5;55~"

[[keyboard.bindings]]
key = "Key8"
mods = "Control"
chars = "\u001b[27;5;56~"

[[keyboard.bindings]]
key = "Key9"
mods = "Control"
chars = "\u001b[27;5;57~"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
chars = "\u001b[27;5;48~"

