import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[shell]
program = "tmux"
args = ["new-session", "-A", "-D", "-s", "main"]

[font]
size = 14

[window]
opacity = 0.9

[font.bold]
family = "BerkeleyMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "BerkeleyMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "BerkeleyMono Nerd Font"
style = "Italic"

[font.normal]
family = "BerkeleyMono Nerd Font"
style = "Regular"


# Key bindings
[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001Bb"  # Send escape sequence for Alt+Left

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001Bf"  # Send escape sequence for Alt+Right

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u001BOH"  # Send escape sequence for Command+Left

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u001BOF"  # Send escape sequence for Command+Right

